name: Cypress Tests

on:
  push:
    branches:
      - part2
  pull_request:
    branches:
      - part2

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cypress Run
        uses: cypress-io/github-action@v7
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}